name: Build Image and Push to ECR

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      subfolder:
        required: true
        type: string
    secrets:
      AWS_REGION:
        required: true
      AWS_ASSUMED_ROLE:
        required: true
      AWS_ECR_URL:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Image and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUMED_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_URL: ${{ secrets.AWS_ECR_URL }}
          REPO: ${{ github.event.repository.name }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          cd ${{ inputs.subfolder }}
          docker build -t $ECR_URL/$REPO:$IMAGE_TAG .
          docker push $ECR_URL/$REPO:$IMAGE_TAG
