name: Deploy Image on Lambda

on:
  workflow_call:
    inputs:
      lambda_script:
        required: true
        type: string
      image:
        required: true
        type: string
    secrets:
      AWS_ASSUMED_ROLE:
        required: true
      AWS_REGION:
        required: true
      AWS_ECR_URL:
        required: true

jobs:
  deploy:
    name: Deploy Image on Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUMED_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Lambda Function
        env:
          FUNCTION_NAME: ${{ inputs.lambda_script }}
          IMAGE_URI: ${{ secrets.AWS_ECR_URL }}/${{ inputs.image }}
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --image-uri $IMAGE_URI
