on:
  workflow_call:
    inputs:
      script_name:
        required: true
        type: string
    secrets:
      AWS_REGION:
        required: true
      AWS_ECR_ROLE:
        required: true
      AWS_LAMBDA_ROLE:
        required: true
      AWS_ECR_URL:
        required: true

jobs:
  build-and-push-ecr:
    uses: qrcapital/shared-ci/.github/workflows/build-image-push-ecr-subfolder.yml@master
    with:
      image_tag: ${{ github.sha }}
      subfolder: ./scripts/${{ inputs.script_name }}/script
      repo: ${{ inputs.script_name }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ASSUMED_ROLE: ${{ secrets.AWS_ECR_ROLE }}
      AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}

  update-lambda:
    needs: build-and-push-ecr
    uses: qrcapital/shared-ci/.github/workflows/deploy-lambda-image.yml@master
    with:
      lambda_script: ${{ inputs.script_name }}
      image: ${{ inputs.script_name }}:${{ github.sha }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ASSUMED_ROLE: ${{ secrets.AWS_LAMBDA_ROLE }}
      AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}
